---  
- name:  Install MySQL
  apt: name={{ item }} state=installed
  with_items:
    - mysql-server
    - python-mysqldb

- name: Set Mysql root password
  mysql_user: check_implicit_admin=yes login_user=root login_password={{ mysqlrootpwd }} name=root password={{ mysqlrootpwd }} state=present
